# Generated by Django 5.1.3 on 2026-01-06 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_rename_is_chosen_checkbox_addattractions_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='passed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(blank=True, max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cartedSpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_spots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.addattractions')),
                ('userPass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pass.passed')),
            ],
        ),
    ]
