# Generated by Django 5.2.10 on 2026-01-22 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartedspots',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cartedspots',
            name='members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartedspots',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
