# Generated by Django 5.1.3 on 2025-12-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addattractions',
            name='user',
        ),
    ]
