# Generated by Django 5.1.3 on 2025-12-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_addattractions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingdata',
            name='visitingSpot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.addattractions'),
        ),
    ]
