# Generated by Django 5.1.3 on 2026-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_visitingdata_visitingspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='addattractions',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addattractions',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='addattractions',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='addattractions',
            name='location',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='addattractions',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
    ]
