# Generated by Django 5.1.3 on 2026-01-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_addattractions_city_addattractions_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addattractions',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addattractions',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='addattractions',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='addattractions',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
