# Generated by Django 5.1.3 on 2026-01-04 02:46

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_addattractions_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addattractions',
            old_name='is_chosen_checkbox',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='addattractions',
            name='image',
        ),
        migrations.CreateModel(
            name='spotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=base.models.upload_path)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.addattractions')),
            ],
        ),
    ]
