# Generated by Django 5.1.3 on 2025-12-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_visitingdata_visitingspot'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourcartitem',
            unique_together={('cart', 'touristSpot', 'start_date', 'end_date')},
        ),
    ]
