# Generated by Django 5.1.3 on 2025-12-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourcartitem',
            unique_together=set(),
        ),
    ]
