# Generated by Django 5.1.3 on 2025-12-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_visitingdata_visitingspot'),
        ('cart', '0005_alter_tourcartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourcartitem',
            unique_together={('cart', 'touristSpot', 'start_date', 'end_date')},
        ),
    ]
