# Generated by Django 5.1.3 on 2026-01-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_visitingdata_visitingspot'),
        ('cart', '0006_alter_tourcartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourcartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tourcartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
        migrations.AlterUniqueTogether(
            name='tourcartitem',
            unique_together={('cart', 'touristSpot')},
        ),
    ]
