# Generated by Django 5.1.3 on 2026-01-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_tourcartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
    ]
